### ISSUE TITLE
Bot posts a new thread and then throws error

### ISSUE THREAD

**Issue by murder** [O-Gourari/FTNBot#2]
When running the bot, it creates theh new thread, but suddenly throws a 403 HTTP error, which in turn makes the bot restart every 60s

```
root@a61d40ac7100:~# python3.7 /root/Bot/bot.py 

Started.
--------
(03:42 - July 15, 2018)  Unexpexted Error: received 403 HTTP response

^CTraceback (most recent call last):
  File "/root/Bot/bot.py", line 123, in main
    thread_obj.edit(text).mod.sticky(bottom=True)
  File "/usr/local/lib/python3.7/site-packages/praw/models/reddit/submission.py", line 404, in sticky
    data=data)
  File "/usr/local/lib/python3.7/site-packages/praw/reddit.py", line 445, in post
    params=params)
  File "/usr/local/lib/python3.7/site-packages/praw/reddit.py", line 486, in request
    params=params)
  File "/usr/local/lib/python3.7/site-packages/prawcore/sessions.py", line 182, in request
    params=params, url=url)
  File "/usr/local/lib/python3.7/site-packages/prawcore/sessions.py", line 127, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Bot/bot.py", line 145, in <module>
    main()
  File "/root/Bot/bot.py", line 141, in main
    time.sleep(1)
KeyboardInterrupt
```

**Comment by O-Gourari** [comment]
the bot need to be a mod so it can stick the post
